#!/usr/bin/env bash

base=$(pwd)
lib="${base}/lib"

year() {
	year="${1}"
	for day in $(seq 1 25); do
		day "${year}" "${day}" || break
	done
}

day() {
	year="${1}"
	day="${2}"
	! test -d "${base}/${year}/${day}" && return 1
	pushd "${base}/${year}/${day}" 1> /dev/null
	echo "Day ${day} of ${year}"
	if ! test -f input; then
		aoc download -I -d $day -y $year
	fi
	for f in main.* a.* b.*; do
		name=${f%.*}
		ext=${f##*.}
		if [ "$ext" = "*" ]; then continue; fi
		"${base}/test/run-${ext}.sh" . "$name" "$lib" || return 1
	done
	popd 1> /dev/null
}

help() {
	echo "Usage:"
	echo "  $0            run tests for every day of every year"
	echo "  $0 year       run tests for every day of <year>"
	echo "  $0 year day   run tests for the nth <day> of <year>"
}

if ! command -v aoc 1> /dev/null; then
	echo aoc cli not found
	exit 1
fi

if ! [ -v ADVENT_OF_CODE_SESSION ]; then
	echo ADVENT_OF_CODE_SESSION is not set
	exit 1
fi

while getopts "h" opt; do
	case "$opt" in
		h) help; return 0 ;;
	esac
done

shift $((OPTIND - 1))

if test "$#" = 1; then
	year "${1}"
	return $?
fi

if test "$#" = 2; then
	day "${1}" "${2}"
	return $?
fi

for year in 20*; do
	year "${year}"
done
