#!/bin/sh

base=$(pwd)

year() {
	year="${1}"
	for day in $(seq 1 25); do
		day "${year}" "${day}" || break
	done
}

day() {
	year="${1}"
	day="${2}"
	! test -d "${base}/${year}/${day}" && return 1
	echo "Day ${day} of ${year}"
	if test -f "${base}/${year}/${day}/main.lua"; then
		"${base}/test/run-lua.sh" "${base}/${year}/${day}" || return 1
	fi
}

if test "$#" = 1; then
	year "${1}"
	return $?
fi

if test "$#" = 2; then
	day "${1}" "${2}"
	return $?
fi

for year in 20*; do
	year "${year}"
done
